/**:
  ros__parameters:
    # --- Safe Workspace Boundaries ---
    # Set to 'true' to strictly enforce table boundaries (recommended for real hardware)
    enable_workspace_safety: true
    # Physical dimensions of the table (in meters relative to robot base), check robot_base_frame TF in RViz for orientation
    workspace_min_x: -0.325
    workspace_max_x:  0.325
    workspace_min_y: -0.24
    workspace_max_y:  0.76
    # Allowed tolerance outside the table (e.g. for dropping items off the edge)
    workspace_safety_tolerance: 0.10

    # --- Camera Topics ---
    camera_info_topic: '/camera/d415/color/camera_info'
    color_image_topic: '/camera/d415/color/image_raw'
    depth_image_topic: '/camera/d415/aligned_depth_to_color/image_raw'

    # --- TF Frames ---
    # Frame of the camera for TF transformations
    camera_frame: 'd415_color_optical_frame'
    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'
