/**:
  ros__parameters:
    # --- Safe Workspace Boundaries ---
    # Set to 'true' to strictly enforce table boundaries (recommended for real hardware)
    enable_workspace_safety: false
    # Physical dimensions of the table (in meters relative to robot base)
    workspace_min_x: -0.40
    workspace_max_x:  0.40
    workspace_min_y:  0.15
    workspace_max_y:  0.60
    # Allowed tolerance outside the table (e.g. for dropping items off the edge)
    workspace_safety_tolerance: 0.10

    # --- Camera Topics ---
    camera_info_topic: '/webots_realsense/depth/image_rect_raw/camera_info'
    color_image_topic: '/webots_realsense/color/image_raw/image_color'
    depth_image_topic: '/webots_realsense/depth/image_rect_raw/image'

    # --- TF Frames ---
    # Frame of the camera for TF transformations
    camera_frame: 'd415_sim_optical_frame'
    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'

