gemini_vision_node:
  ros__parameters:
    # --- Camera Topics ---
    camera_info_topic: '/webots_realsense/depth/image_rect_raw/camera_info'
    depth_image_topic: '/webots_realsense/depth/image_rect_raw/image'
    color_image_topic: '/webots_realsense/color/image_raw/image_color'

    # Frame of the camera for TF transformations
    camera_frame: 'd415_sim_optical_frame'

    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'

