color_detector_node:
  ros__parameters:
    # --- Camera Topics ---
    camera_info_topic: '/camera/d415/color/camera_info'
    color_image_topic: '/camera/d415/color/image_raw'
    depth_image_topic: '/camera/d415/aligned_depth_to_color/image_raw'

    # Frame of the camera for TF transformations
    camera_frame: 'd415_color_optical_frame'

    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'