color_detector_node:
  ros__parameters:
    # --- Camera Topics & Frames ---´
    camera_info_topic: '/camera/aligned_depth_to_color/camera_info'
    depth_image_topic: '/camera/aligned_depth_to_color/image_raw'
    color_image_topic: '/camera/color/image_raw'
    camera_frame: 'camera_color_optical_frame'

    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'

    # --- HSV Color Thresholds ---
    hsv_red_lower: [124, 183, 121]
    hsv_red_upper: [179, 255, 255]
    
    hsv_yellow_lower: [16, 128, 117]
    hsv_yellow_upper: [53, 255, 255]
    
    hsv_green_lower: [40, 83, 0]
    hsv_green_upper: [80, 255, 255]

    hsv_blue_lower: [32, 81, 175]
    hsv_blue_upper: [147, 255, 255]