color_detector_node:
  ros__parameters:
    # --- Camera Topics & Frames ---
    camera_info_topic: '/webots_realsense/depth/image_rect_raw/camera_info'
    depth_image_topic: '/webots_realsense/depth/image_rect_raw/image'
    color_image_topic: '/webots_realsense/color/image_raw/image_color'
    camera_frame_id: 'd415_sim_optical_frame'

    # Target frame for the 3D coordinates
    robot_base_frame: 'ur5e_base_link'

    # --- HSV Color Thresholds ---
    hsv_red_lower: [124, 183, 121]
    hsv_red_upper: [179, 255, 255]
    
    hsv_yellow_lower: [16, 128, 117]
    hsv_yellow_upper: [53, 255, 255]
    
    hsv_green_lower: [40, 83, 0]
    hsv_green_upper: [80, 255, 255]

    hsv_blue_lower: [32, 81, 175]
    hsv_blue_upper: [147, 255, 255]
